MODULE := core
# Link tests against dependent modules used by core tests
TEST_LIBS = $(LIB_DIR)/libcore.a $(LIB_DIR)/liblock.a $(LIB_DIR)/libtypes.a $(LIB_DIR)/libbeacon.a $(LIB_DIR)/libevent.a $(LIB_DIR)/libstorage.a $(LIB_DIR)/libdht.a $(LIB_DIR)/libbittorrent.a $(LIB_DIR)/libtracker.a $(LIB_DIR)/libnetwork.a $(LIB_DIR)/libbencode.a
include ../module.mk
